name: Build Tuuna Agent

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Linux System Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk python3-dev scrot python3-xlib xvfb tcl-dev tk-dev libx11-dev

    - name: Install macOS Dependencies

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install python-tk
        pip install pyobjc-core pyobjc

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Windows Extras
      if: runner.os == 'Windows'
      run: pip install pypiwin32 winshell pywin32

    - name: Build with PyInstaller
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          xvfb-run -a python build_exe.py
        else
          python build_exe.py
        fi
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4  # Using v4 for better performance
      with:
        name: Tuuna-Agent-${{ runner.os }}
        path: dist/
